/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.analysis


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class AlgaeStandaloneSetup extends AlgaeStandaloneSetupGenerated {

	def static void doSetup() {
		new AlgaeStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
