/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.analysis.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractAlgaeScopeProvider extends DelegatingScopeProvider {
}
