/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.analysis.ide

import com.google.inject.Guice
import org.atlanmod.analysis.AlgaeRuntimeModule
import org.atlanmod.analysis.AlgaeStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class AlgaeIdeSetup extends AlgaeStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new AlgaeRuntimeModule, new AlgaeIdeModule))
	}
	
}
