/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.analysis.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class AlgaeScopeProvider extends AbstractAlgaeScopeProvider {

}
