/**
 */
package org.atlanmod.analysis.algae.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.atlanmod.analysis.algae.util.AlgaeAdapterFactory;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class AlgaeItemProviderAdapterFactory extends AlgaeAdapterFactory implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public AlgaeItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.Platform} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected PlatformItemProvider platformItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.Platform}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createPlatformAdapter() {
		if (platformItemProvider == null) {
			platformItemProvider = new PlatformItemProvider(this);
		}

		return platformItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.Variable} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected VariableItemProvider variableItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.Variable}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createVariableAdapter() {
		if (variableItemProvider == null) {
			variableItemProvider = new VariableItemProvider(this);
		}

		return variableItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureValue} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureValueItemProvider measureValueItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureValue}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureValueAdapter() {
		if (measureValueItemProvider == null) {
			measureValueItemProvider = new MeasureValueItemProvider(this);
		}

		return measureValueItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureOCL} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureOCLItemProvider measureOCLItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureOCL}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureOCLAdapter() {
		if (measureOCLItemProvider == null) {
			measureOCLItemProvider = new MeasureOCLItemProvider(this);
		}

		return measureOCLItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureAttribute} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureAttributeItemProvider measureAttributeItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureAttribute}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureAttributeAdapter() {
		if (measureAttributeItemProvider == null) {
			measureAttributeItemProvider = new MeasureAttributeItemProvider(this);
		}

		return measureAttributeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureCast} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureCastItemProvider measureCastItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureCast}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureCastAdapter() {
		if (measureCastItemProvider == null) {
			measureCastItemProvider = new MeasureCastItemProvider(this);
		}

		return measureCastItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.RealTimeDuration} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected RealTimeDurationItemProvider realTimeDurationItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.RealTimeDuration}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createRealTimeDurationAdapter() {
		if (realTimeDurationItemProvider == null) {
			realTimeDurationItemProvider = new RealTimeDurationItemProvider(this);
		}

		return realTimeDurationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureUnboundSumOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureUnboundSumOperationItemProvider measureUnboundSumOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureUnboundSumOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureUnboundSumOperationAdapter() {
		if (measureUnboundSumOperationItemProvider == null) {
			measureUnboundSumOperationItemProvider = new MeasureUnboundSumOperationItemProvider(this);
		}

		return measureUnboundSumOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureUnboundSubstractOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureUnboundSubstractOperationItemProvider measureUnboundSubstractOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureUnboundSubstractOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureUnboundSubstractOperationAdapter() {
		if (measureUnboundSubstractOperationItemProvider == null) {
			measureUnboundSubstractOperationItemProvider = new MeasureUnboundSubstractOperationItemProvider(this);
		}

		return measureUnboundSubstractOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureUnboundProductOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureUnboundProductOperationItemProvider measureUnboundProductOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureUnboundProductOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureUnboundProductOperationAdapter() {
		if (measureUnboundProductOperationItemProvider == null) {
			measureUnboundProductOperationItemProvider = new MeasureUnboundProductOperationItemProvider(this);
		}

		return measureUnboundProductOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasureUnboundDivisionOperation} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasureUnboundDivisionOperationItemProvider measureUnboundDivisionOperationItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasureUnboundDivisionOperation}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasureUnboundDivisionOperationAdapter() {
		if (measureUnboundDivisionOperationItemProvider == null) {
			measureUnboundDivisionOperationItemProvider = new MeasureUnboundDivisionOperationItemProvider(this);
		}

		return measureUnboundDivisionOperationItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.MeasurementUncertainty} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MeasurementUncertaintyItemProvider measurementUncertaintyItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.MeasurementUncertainty}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMeasurementUncertaintyAdapter() {
		if (measurementUncertaintyItemProvider == null) {
			measurementUncertaintyItemProvider = new MeasurementUncertaintyItemProvider(this);
		}

		return measurementUncertaintyItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.NormalDistribution} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected NormalDistributionItemProvider normalDistributionItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.NormalDistribution}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createNormalDistributionAdapter() {
		if (normalDistributionItemProvider == null) {
			normalDistributionItemProvider = new NormalDistributionItemProvider(this);
		}

		return normalDistributionItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.Interval} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntervalItemProvider intervalItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.Interval}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntervalAdapter() {
		if (intervalItemProvider == null) {
			intervalItemProvider = new IntervalItemProvider(this);
		}

		return intervalItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.Sampling} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SamplingItemProvider samplingItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.Sampling}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSamplingAdapter() {
		if (samplingItemProvider == null) {
			samplingItemProvider = new SamplingItemProvider(this);
		}

		return samplingItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.Integral} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegralItemProvider integralItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.Integral}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegralAdapter() {
		if (integralItemProvider == null) {
			integralItemProvider = new IntegralItemProvider(this);
		}

		return integralItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.Sample} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SampleItemProvider sampleItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.Sample}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createSampleAdapter() {
		if (sampleItemProvider == null) {
			sampleItemProvider = new SampleItemProvider(this);
		}

		return sampleItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.LogisticMeasure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected LogisticMeasureItemProvider logisticMeasureItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.LogisticMeasure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createLogisticMeasureAdapter() {
		if (logisticMeasureItemProvider == null) {
			logisticMeasureItemProvider = new LogisticMeasureItemProvider(this);
		}

		return logisticMeasureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.ExponentialMeasure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ExponentialMeasureItemProvider exponentialMeasureItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.ExponentialMeasure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createExponentialMeasureAdapter() {
		if (exponentialMeasureItemProvider == null) {
			exponentialMeasureItemProvider = new ExponentialMeasureItemProvider(this);
		}

		return exponentialMeasureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.atlanmod.analysis.algae.IntegrationMeasure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IntegrationMeasureItemProvider integrationMeasureItemProvider;

	/**
	 * This creates an adapter for a {@link org.atlanmod.analysis.algae.IntegrationMeasure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createIntegrationMeasureAdapter() {
		if (integrationMeasureItemProvider == null) {
			integrationMeasureItemProvider = new IntegrationMeasureItemProvider(this);
		}

		return integrationMeasureItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>)type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (platformItemProvider != null) platformItemProvider.dispose();
		if (variableItemProvider != null) variableItemProvider.dispose();
		if (measureValueItemProvider != null) measureValueItemProvider.dispose();
		if (measureOCLItemProvider != null) measureOCLItemProvider.dispose();
		if (measureAttributeItemProvider != null) measureAttributeItemProvider.dispose();
		if (measureCastItemProvider != null) measureCastItemProvider.dispose();
		if (realTimeDurationItemProvider != null) realTimeDurationItemProvider.dispose();
		if (measureUnboundSumOperationItemProvider != null) measureUnboundSumOperationItemProvider.dispose();
		if (measureUnboundSubstractOperationItemProvider != null) measureUnboundSubstractOperationItemProvider.dispose();
		if (measureUnboundProductOperationItemProvider != null) measureUnboundProductOperationItemProvider.dispose();
		if (measureUnboundDivisionOperationItemProvider != null) measureUnboundDivisionOperationItemProvider.dispose();
		if (measurementUncertaintyItemProvider != null) measurementUncertaintyItemProvider.dispose();
		if (normalDistributionItemProvider != null) normalDistributionItemProvider.dispose();
		if (intervalItemProvider != null) intervalItemProvider.dispose();
		if (samplingItemProvider != null) samplingItemProvider.dispose();
		if (integralItemProvider != null) integralItemProvider.dispose();
		if (sampleItemProvider != null) sampleItemProvider.dispose();
		if (logisticMeasureItemProvider != null) logisticMeasureItemProvider.dispose();
		if (exponentialMeasureItemProvider != null) exponentialMeasureItemProvider.dispose();
		if (integrationMeasureItemProvider != null) integrationMeasureItemProvider.dispose();
	}

}
