/*
 * generated by Xtext 2.14.0
 */
package org.atlanmod.analysis.parser.antlr;

import com.google.inject.Inject;
import org.atlanmod.analysis.parser.antlr.internal.InternalAlgaeParser;
import org.atlanmod.analysis.services.AlgaeGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class AlgaeParser extends AbstractAntlrParser {

	@Inject
	private AlgaeGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalAlgaeParser createParser(XtextTokenStream stream) {
		return new InternalAlgaeParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Platform";
	}

	public AlgaeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(AlgaeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
